"""add lecturer competencies

Revision ID: 17287af79cc5
Revises: d72f54ef2d05
Create Date: 2026-01-08 23:21:00.846399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17287af79cc5'
down_revision: Union[str, Sequence[str], None] = 'd72f54ef2d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturers', sa.Column('competencies', postgresql.ARRAY(sa.String(length=255)), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturers', 'competencies')
    # ### end Alembic commands ###
