"""add email column to users table

Revision ID: 4ef06b131b1f
Revises: 9be923b42de7
Create Date: 2026-01-09 09:34:40.169636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef06b131b1f'
down_revision: Union[str, Sequence[str], None] = '9be923b42de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint(op.f('identities_username_key'), 'identities', type_='unique')
    op.create_unique_constraint(None, 'identities', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('identities_email_key', 'identities', type_='unique')
    op.create_unique_constraint(op.f('identities_username_key'), 'identities', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('identities', 'email')
    # ### end Alembic commands ###
