"""remove association ids

Revision ID: 697c7a108938
Revises: 9625cbdb960d
Create Date: 2026-01-07 20:13:18.476903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697c7a108938'
down_revision: Union[str, Sequence[str], None] = '9625cbdb960d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_course_category'), 'course_categories', type_='unique')
    op.drop_column('course_categories', 'association_id')
    op.drop_constraint(op.f('uq_course_lecturer'), 'course_lecturers', type_='unique')
    op.drop_column('course_lecturers', 'association_id')
    op.drop_constraint(op.f('uq_course_skill'), 'course_skills', type_='unique')
    op.drop_column('course_skills', 'association_id')
    op.drop_constraint(op.f('uq_course_tag'), 'course_tags', type_='unique')
    op.drop_column('course_tags', 'association_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_tags', sa.Column('association_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_course_tag'), 'course_tags', ['course_id', 'tag_id'], postgresql_nulls_not_distinct=False)
    op.add_column('course_skills', sa.Column('association_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_course_skill'), 'course_skills', ['course_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    op.add_column('course_lecturers', sa.Column('association_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_course_lecturer'), 'course_lecturers', ['course_id', 'lecturer_id'], postgresql_nulls_not_distinct=False)
    op.add_column('course_categories', sa.Column('association_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_course_category'), 'course_categories', ['course_id', 'category_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
