"""reduce course

Revision ID: 78fa1d882248
Revises: 0765612cc6b0
Create Date: 2026-01-07 00:39:41.064499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fa1d882248'
down_revision: Union[str, Sequence[str], None] = '0765612cc6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_code_key'), 'courses', type_='unique')
    op.drop_column('courses', 'code')
    op.drop_column('courses', 'target_audience')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('target_audience', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('courses_code_key'), 'courses', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
