"""add discounted cost

Revision ID: 951cbd11dcd0
Revises: 71b440f8feb5
Create Date: 2026-01-07 01:05:09.344790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951cbd11dcd0'
down_revision: Union[str, Sequence[str], None] = '71b440f8feb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('discounted_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'discounted_cost')
    # ### end Alembic commands ###
