"""enrich course entity

Revision ID: b388eb4c2eca
Revises: 17287af79cc5
Create Date: 2026-01-09 00:24:09.388287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b388eb4c2eca'
down_revision: Union[str, Sequence[str], None] = '17287af79cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('education_format', sa.Enum('GROUP', 'INDIVIDUAL', 'SELF_PACED', 'MENTORLED', 'COHORT', name='educationformat'), nullable=False))
    op.add_column('courses', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('locations', postgresql.ARRAY(sa.String(length=255)), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'locations')
    op.drop_column('courses', 'end_date')
    op.drop_column('courses', 'education_format')
    # ### end Alembic commands ###
