"""add cascade deletes

Revision ID: d713d8275e84
Revises: c0c9a4bde5e6
Create Date: 2026-01-08 02:09:33.261145

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d713d8275e84"
down_revision: Union[str, Sequence[str], None] = "c0c9a4bde5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("course_categories_course_id_fkey"),
        "course_categories",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "course_categories",
        "courses",
        ["course_id"],
        ["course_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("course_sections_course_id_fkey"), "course_sections", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "course_sections",
        "courses",
        ["course_id"],
        ["course_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("course_skills_course_id_fkey"), "course_skills", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "course_skills",
        "courses",
        ["course_id"],
        ["course_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("course_tags_course_id_fkey"), "course_tags", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "course_tags", "courses", ["course_id"], ["course_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("course_tags_course_id_fkey"), "course_tags", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("course_tags_course_id_fkey"),
        "course_tags",
        "courses",
        ["course_id"],
        ["course_id"],
    )
    op.drop_constraint(
        op.f("course_skills_course_id_fkey"), "course_skills", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("course_skills_course_id_fkey"),
        "course_skills",
        "courses",
        ["course_id"],
        ["course_id"],
    )
    op.drop_constraint(
        op.f("course_sections_course_id_fkey"), "course_sections", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("course_sections_course_id_fkey"),
        "course_sections",
        "courses",
        ["course_id"],
        ["course_id"],
    )
    op.drop_constraint(
        op.f("course_categories_course_id_fkey"),
        "course_categories",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("course_categories_course_id_fkey"),
        "course_categories",
        "courses",
        ["course_id"],
        ["course_id"],
    )
    # ### end Alembic commands ###
